# Generated by Django 5.1.2 on 2024-11-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsstatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
