# Generated by Django 5.1.2 on 2024-11-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0005_feedbackreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreg',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
