# Generated by Django 5.1.2 on 2024-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_alter_feedbackreg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreg',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
