# Generated by Django 5.1.2 on 2024-11-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0007_alter_feedbackreg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('Real', 'real'), ('Fake', 'fake')], max_length=10)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detect.userreg')),
            ],
        ),
    ]
