# Generated by Django 5.1.2 on 2024-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0008_reportnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='us_behave',
            field=models.CharField(blank=True, default='Posts an equal mix of real and fake news', max_length=50, null=True),
        ),
    ]
