# Generated by Django 5.1.2 on 2025-02-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0011_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
