# Generated by Django 5.1.2 on 2025-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0012_news_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Local News', 'Local News'), ('Technology', 'Technology'), ('Business', 'Business')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
