# Generated by Django 5.1.2 on 2025-03-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0014_news_news_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
